name: ai_text_editor
description: "A new Flutter project."
publish_to: 'none' 

version: 2.0.0+dev1

environment:
  sdk: ^3.6.1


dependencies:
  ai_packages_core: ^0.0.1+1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  daynightbanner: ^0.0.2
  dropdown_button2: ^2.3.9
  extended_image: ^9.1.0
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_quill: ^10.8.5
  flutter_riverpod: ^2.6.1
  flutter_rust_bridge: 2.8.0
  get_time_ago: ^2.2.0
  go_router: ^14.8.0
  gpt_markdown: ^1.0.11
  he: ^0.0.2+1
  langchain: ^0.7.7+2
  langchain_openai: ^0.7.3
  listview_screenshot: ^3.2.0
  logger: ^2.5.0
  markdown_quill: ^4.2.0
  markdown_to_pdf:
    git:
      url: https://github.com/guchengxi1994/markdown_to_pdf.git
      ref: df5832370fa6f460c335a498566a150fcc9895bc
  menu_bar: ^0.5.3
  objectbox: ^4.1.0
  objectbox_flutter_libs: any
  riverpod: ^2.6.1
  rust_lib_ai_text_editor:
    path: rust_builder
  screenshot: ^3.0.0
  toastification: ^2.3.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  integration_test:
    sdk: flutter
  objectbox_generator: any

flutter:
  uses-material-design: true


  assets:
    - assets/config.json
    - assets/prompts/spell-check-prompt.txt

  fonts:
    - family: HanSansCN
      fonts:
        - asset: assets/fonts/SourceHanSansCN-Bold.ttf
        - asset: assets/fonts/SourceHanSansCN-Regular.ttf
    
    - family: emoji
      fonts:
        - asset: assets/fonts/NotoEmoji-VariableFont_wght.ttf
    
    - family: song
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
