[package]
name = "rust_lib_ai_text_editor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
docx-converter = {version = "0.1.0", path = "../plugins/docx-converter"}